// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TEACHER_MYAPP_H_
#define FLATBUFFERS_GENERATED_TEACHER_MYAPP_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

namespace MyApp {

struct Teacher;
struct TeacherBuilder;

struct Teacher FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TeacherBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_AGE = 6
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  int32_t age() const {
    return GetField<int32_t>(VT_AGE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int32_t>(verifier, VT_AGE, 4) &&
           verifier.EndTable();
  }
};

struct TeacherBuilder {
  typedef Teacher Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Teacher::VT_NAME, name);
  }
  void add_age(int32_t age) {
    fbb_.AddElement<int32_t>(Teacher::VT_AGE, age, 0);
  }
  explicit TeacherBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Teacher> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Teacher>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Teacher> CreateTeacher(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    int32_t age = 0) {
  TeacherBuilder builder_(_fbb);
  builder_.add_age(age);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Teacher> CreateTeacherDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    int32_t age = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return MyApp::CreateTeacher(
      _fbb,
      name__,
      age);
}

inline const MyApp::Teacher *GetTeacher(const void *buf) {
  return ::flatbuffers::GetRoot<MyApp::Teacher>(buf);
}

inline const MyApp::Teacher *GetSizePrefixedTeacher(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<MyApp::Teacher>(buf);
}

inline bool VerifyTeacherBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<MyApp::Teacher>(nullptr);
}

inline bool VerifySizePrefixedTeacherBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<MyApp::Teacher>(nullptr);
}

inline void FinishTeacherBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<MyApp::Teacher> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedTeacherBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<MyApp::Teacher> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace MyApp

#endif  // FLATBUFFERS_GENERATED_TEACHER_MYAPP_H_
